
const K="sj_v10_finale_data", OLD=["sj_v10_corrigee_data","sj_v10_definitive_data","sj_v9_google_data","sj_v8_finale_data","sj_v7_definitive_data"];
const N=["Nadège","Camille & Benoît","Thierry","Serge","Hélène","Juliette","Céline","Cabinet d'infirmières","Dorothée & Laurent","Élodie","Maryse","Véronique","Jean-Christophe","Nicole","Aymeric","Daniel","Jean-Claude","Richard","Kath","Floriane & Max"];
const uid=()=>crypto?.randomUUID?crypto.randomUUID():"id"+Date.now()+Math.random();
const def=()=>({version:"v10-finale",month:new Date().toISOString().slice(0,7),current:null,settings:{hourRate:16,machinePrice:2.5},google:{clientId:"",accessToken:"",expiresAt:0,email:"steph.jenny.menagecesu@gmail.com"},clients:N.map((name,i)=>({id:uid(),ref:String(i+1).padStart(3,"0"),name,phone:"",address:"",type:name==="Floriane & Max"?"Location saisonnière":"CESU",rate:16,notes:""})),interventions:[],planning:[],reports:{},closures:{}});
function merge(a,b){for(const k in b)a[k]=typeof b[k]=="object"&&!Array.isArray(b[k])&&b[k]?merge(a[k]||{},b[k]):b[k];return a}
function load(){try{let x=JSON.parse(localStorage.getItem(K));if(x)return merge(def(),x);for(const k of OLD){let o=localStorage.getItem(k);if(o){x=merge(def(),JSON.parse(o));localStorage.setItem(K,JSON.stringify(x));return x}}}catch(e){}return def()}
let db=load(), screen="home", timer=null, tokenClient=null; const save=()=>localStorage.setItem(K,JSON.stringify(db));
const $=q=>document.querySelector(q), pad=n=>String(n).padStart(2,"0"), today=()=>new Date().toISOString().slice(0,10);
const euros=n=>Number(n||0).toFixed(2).replace(".",",")+" €", fd=s=>new Date(s+"T00:00:00").toLocaleDateString("fr-FR"), ft=d=>pad(d.getHours())+":"+pad(d.getMinutes());
const dur=(a,b)=>Math.max(0,Math.ceil((new Date(b)-new Date(a))/60000)), fmin=m=>(m<0?"-":"")+Math.floor(Math.abs(m)/60)+"h"+pad(Math.abs(m)%60);
const hms=ms=>{let s=Math.floor(Math.max(0,ms)/1000),h=Math.floor(s/3600);s-=h*3600;let m=Math.floor(s/60);s-=m*60;return pad(h)+":"+pad(m)+":"+pad(s)}
const month=(list=db.interventions)=>list.filter(x=>x.date?.startsWith(db.month)), clients=()=>db.clients.filter(c=>!c.archived), client=n=>db.clients.find(c=>c.name===n)||{rate:db.settings.hourRate};
function worker(w){return w==="stephanie"?"Stéphanie":w==="jennyfer"?"Jennyfer":"À deux"}function mins(items,w){return items.filter(x=>x.worker==="deux"||x.worker===w).reduce((a,x)=>a+(+x.duration||0),0)}
function machines(items){return items.filter(x=>x.client==="Floriane & Max").reduce((a,x)=>a+(+x.machines||0),0)}function machFor(w){return w==="stephanie"||w==="jennyfer"?machines(month().filter(x=>x.worker==="deux"||x.worker===w))/2:machines(month())}
function decl(m){let h=Math.floor(Math.abs(m)/60),r=Math.abs(m)%60,sg=m<0?-1:1;return sg*(r>=31?h+1:h)}
function rkey(c,w,m=db.month){return c+"|"+m+"|"+w}function getR(c,w,m=db.month){return +(db.reports?.[rkey(c,w,m)]||0)}function setR(c,w,v,m=db.month){db.reports[rkey(c,w,m)]=+v||0;save()}
function calc(c,w,raw){let rep=getR(c,w),adj=raw+rep,d=decl(adj),next=adj-d*60;return{rep,adj,d,next}}function rt(m){return m===0?"0 min":(m>0?"+":"")+m+" min"}
function go(s){screen=s;render()}function nav(){return `<div class=nav><button onclick="go('home')">🏠<br>Accueil</button><button onclick="go('chrono')">⏱️<br>Chrono</button><button onclick="go('planning')">📅<br>Plan.</button><button onclick="go('clients')">👥<br>Clients</button><button onclick="go('settings')">⚙️<br>Réglages</button></div>`}
function layout(c){if(timer)clearInterval(timer);timer=null;app.innerHTML=`<main class=app>${c}${nav()}</main>`}function render(){({home,chrono,clients:clientsPage,planning,google,allRecap,clientRecap,payroll,reports,closure,interventions,flomax,settings}[screen]||home)()}
function totals(){let ts=0,tj=0,ms=0,mj=0,es=0,ej=0;names().forEach(n=>{let d=rowData(n),rate=d.rate;ts+=d.cs.d;tj+=d.cj.d;es+=d.cs.d*rate;ej+=d.cj.d*rate});let mf=machines(month());ms=mf/2;mj=mf/2;es+=ms*db.settings.machinePrice;ej+=mj*db.settings.machinePrice;return{ts,tj,ms,mj,es,ej,total:es+ej,mt:mf}}
function home(){let it=month(),s=mins(it,"stephanie"),j=mins(it,"jennyfer"),t=totals();layout(`<div class=hero><div class=logo>Steph & Jenny</div><div class=sub>GESTION V10 FINALE</div><p>${new Date().toLocaleDateString("fr-FR",{weekday:"long",day:"numeric",month:"long"})}</p></div>${db.current?`<div class="card notice"><h2>Chrono en cours</h2><p>${db.current.client} • ${worker(db.current.worker)}</p><div class=chrono id=t>00:00:00</div><button class="big stop" onclick=stopWork()>⏹ Terminer</button></div>`:`<button class=big onclick="go('chrono')">⏱️ Ouvrir le chronomètre</button>`}<div class=grid><button onclick="go('allRecap')">📋 Récap tous clients</button><button onclick="go('clientRecap')">👤 Récap client</button><button onclick="go('payroll')">💶 Fiche paie</button><button onclick="go('reports')">🔁 Reports</button><button onclick="go('closure')">🔒 Clôture mois</button><button onclick="go('interventions')">✏️ Heures</button><button onclick="go('flomax')">🏡 Flo & Max</button><button onclick="go('google')">📅 Google</button></div><div class=card><div class=grid3><div class=stat><strong>${fmin(s)}</strong><span>Stéphanie</span></div><div class=stat><strong>${fmin(j)}</strong><span>Jennyfer</span></div><div class=stat><strong>${machines(it)}</strong><span>machines</span></div></div></div><div class="card ok"><h3>Montants estimés</h3><p>Stéphanie : <b>${euros(t.es)}</b></p><p>Jennyfer : <b>${euros(t.ej)}</b></p><p>Total : <b>${euros(t.total)}</b></p></div>`);if(db.current)live("t")}
function chrono(){let opts=clients().map(c=>`<option>${c.name}</option>`).join("");layout(`<button onclick="go('home')">← Retour</button><h2>Chronomètre</h2>${db.current?`<div class="card notice"><h3>${db.current.client}</h3><p>${worker(db.current.worker)}</p><div class=chrono id=live>00:00:00</div><button class="big stop" onclick=stopWork()>⏹ Arrêter et enregistrer</button><button onclick=cancelWork()>Annuler</button></div>`:`<div class=card><label>Client</label><select id=cc onchange="showRep();machBox()">${opts}</select><label>Qui ?</label><select id=cw onchange=showRep()><option value=deux>À deux</option><option value=stephanie>Stéphanie seule</option><option value=jennyfer>Jennyfer seule</option></select><div id=rep class="card ok"></div><label>Type</label><select id=ct><option>Ménage</option><option>Location saisonnière</option><option>Machine</option><option>Repassage</option></select><div id=mb class="card notice"><label>Machines Flo & Max</label><input id=cm type=number value=0></div><label>Notes</label><textarea id=cn></textarea><button class=big onclick=startChrono()>▶ Démarrer</button></div>`}<div class=card><button class=blue onclick=editInter()>➕ Saisie manuelle</button></div>`);machBox();showRep();if(db.current)live("live")}
function live(id){let e=()=>document.getElementById(id);let up=()=>{if(e()&&db.current)e().textContent=hms(Date.now()-new Date(db.current.start).getTime())};up();timer=setInterval(up,1000)}
function showRep(){if(!$("#rep")||!$("#cc"))return;let c=$("#cc").value,w=$("#cw").value;$("#rep").innerHTML=w==="deux"?`Reports actuels<br>Stéphanie : <b>${rt(getR(c,"stephanie"))}</b><br>Jennyfer : <b>${rt(getR(c,"jennyfer"))}</b>`:`Report ${worker(w)} : <b>${rt(getR(c,w))}</b>`}
function machBox(){if($("#mb"))$("#mb").style.display=$("#cc")?.value==="Floriane & Max"?"block":"none"}function startChrono(){let c=$("#cc").value;db.current={client:c,worker:$("#cw").value,type:$("#ct").value,machines:c==="Floriane & Max"?(+$("#cm").value||0):0,note:$("#cn").value,start:new Date().toISOString()};save();go("chrono")}
function cancelWork(){db.current=null;save();go("chrono")}function stopWork(){let end=new Date().toISOString();db.interventions.push({...db.current,id:uid(),end,date:db.current.start.slice(0,10),duration:dur(db.current.start,end)});db.current=null;save();alert("Intervention enregistrée.");go("interventions")}
function names(){return [...new Set(month().map(x=>x.client))].sort((a,b)=>a.localeCompare(b))}
function rowData(n){let it=month().filter(x=>x.client===n),rs=mins(it,"stephanie"),rj=mins(it,"jennyfer"),cs=calc(n,"stephanie",rs),cj=calc(n,"jennyfer",rj),m=n==="Floriane & Max"?machines(it):0,rate=client(n).rate||db.settings.hourRate;return{it,rs,rj,cs,cj,m,rate,totalS:cs.d*rate,totalJ:cj.d*rate,totalM:m*db.settings.machinePrice,total:(cs.d+cj.d)*rate+m*db.settings.machinePrice}}
function allRecap(){let t=totals(),rows=names().map(n=>{let d=rowData(n);return `<tr><td><b>${n}</b></td><td>${fmin(d.rs)}<br>Début ${rt(d.cs.rep)}<br>Déclarer <b>${d.cs.d}h</b><br>Fin ${rt(d.cs.next)}<br><b>${euros(d.totalS)}</b></td><td>${fmin(d.rj)}<br>Début ${rt(d.cj.rep)}<br>Déclarer <b>${d.cj.d}h</b><br>Fin ${rt(d.cj.next)}<br><b>${euros(d.totalJ)}</b></td><td>${d.m?d.m+"<br>"+euros(d.totalM):"-"}</td><td>${euros(d.total)}</td></tr>`}).join("");layout(`<button onclick="go('home')">← Retour</button><h2>Récap tous les clients</h2><div class="card ok"><h3>Stéphanie</h3><p>Heures : <b>${t.ts}h</b></p><p>Machines : <b>${t.ms}</b></p><p class=money>${euros(t.es)}</p><hr><h3>Jennyfer</h3><p>Heures : <b>${t.tj}h</b></p><p>Machines : <b>${t.mj}</b></p><p class=money>${euros(t.ej)}</p><hr><h3>Total</h3><p>Machines : <b>${t.mt}</b></p><p class=money>${euros(t.total)}</p></div><div class="card tableWrap"><table><tr><th>Client</th><th>Stéphanie</th><th>Jennyfer</th><th>Machines</th><th>Total</th></tr>${rows||"<tr><td colspan=5>Aucune intervention.</td></tr>"}</table></div><button class=big onclick=window.print()>🖨️ PDF</button>`)}
function payroll(){allRecap()}
function clientRecap(n){n=n||clients()[0]?.name;let d=rowData(n);layout(`<button onclick="go('home')">← Retour</button><h2>Récap client</h2><select onchange="clientRecap(this.value)">${db.clients.map(c=>`<option ${c.name===n?"selected":""}>${c.name}</option>`).join("")}</select><div class=card><h2>${n}</h2><table><tr><th>Date</th><th>Arrivée</th><th>Départ</th><th>Durée</th><th>Qui</th></tr>${d.it.map(x=>`<tr><td>${fd(x.date)}</td><td>${ft(new Date(x.start))}</td><td>${ft(new Date(x.end))}</td><td>${fmin(x.duration)}</td><td>${worker(x.worker)}</td></tr>`).join("")}</table><h3>Stéphanie</h3><p>Réel ${fmin(d.rs)} • report début ${rt(d.cs.rep)} • à déclarer ${d.cs.d}h • report fin ${rt(d.cs.next)} • montant ${euros(d.totalS)}</p><h3>Jennyfer</h3><p>Réel ${fmin(d.rj)} • report début ${rt(d.cj.rep)} • à déclarer ${d.cj.d}h • report fin ${rt(d.cj.next)} • montant ${euros(d.totalJ)}</p>${d.m?`<p>Machines : ${d.m} = ${euros(d.totalM)}</p>`:""}</div><button class=big onclick=window.print()>🖨️ PDF</button>`)}
function reports(){let c=$("#rc")?.value||clients()[0]?.name||"";layout(`<button onclick="go('home')">← Retour</button><h2>Reports à reprendre</h2><div class="card notice"><p>+24 min = 24, à déduire 29 min = -29.</p></div><label>Client</label><select id=rc onchange=reports()>${clients().map(x=>`<option ${x.name===c?"selected":""}>${x.name}</option>`).join("")}</select><div class=card><h3>${c}</h3><label>Report Stéphanie en minutes</label><input id=rs type=number value="${getR(c,"stephanie")}"><label>Report Jennyfer en minutes</label><input id=rj type=number value="${getR(c,"jennyfer")}"><button class=big onclick="saveRep('${c.replaceAll("'","\\'")}')">💾 Enregistrer</button></div>`)}
function saveRep(c){setR(c,"stephanie",+$("#rs").value||0);setR(c,"jennyfer",+$("#rj").value||0);alert("Reports enregistrés.");reports()}
function closure(){let rows=names().map(n=>{let d=rowData(n);return `<tr><td>${n}</td><td>${rt(d.cs.next)}</td><td>${rt(d.cj.next)}</td></tr>`}).join("");layout(`<button onclick="go('home')">← Retour</button><h2>Clôture fin de mois</h2><div class=card><p>Copie les reports positifs ou négatifs vers le mois suivant.</p></div><div class="card tableWrap"><table><tr><th>Client</th><th>Report Stéphanie</th><th>Report Jennyfer</th></tr>${rows||"<tr><td colspan=3>Aucune intervention.</td></tr>"}</table></div><button class="big stop" onclick=closeMonth()>🔒 Clôturer</button>`)}
function nextM(m){let[y,mo]=m.split("-").map(Number);mo++;if(mo==13){mo=1;y++}return y+"-"+pad(mo)}function closeMonth(){if(!confirm("Clôturer le mois ?"))return;let nm=nextM(db.month);db.closures[db.month]={closedAt:new Date().toISOString(),nextMonth:nm};names().forEach(n=>{let d=rowData(n);setR(n,"stephanie",d.cs.next,nm);setR(n,"jennyfer",d.cj.next,nm)});save();alert("Reports prêts pour "+nm)}
function clientsPage(){layout(`<button onclick="go('home')">← Retour</button><h2>Clients</h2><button class=big onclick=clientForm()>➕ Ajouter</button>${db.clients.map(c=>`<div class=item><b>${c.name}</b><p>${c.phone||""}<br>${c.address||""}</p><div class=grid><button onclick="clientForm('${c.id}')">✏️ Fiche</button><button onclick="clientRecap('${c.name.replaceAll("'","\\'")}')">📄 Récap</button></div></div>`).join("")}`)}
function clientForm(id){let c=id?db.clients.find(x=>x.id===id):{};layout(`<button onclick="go('clients')">← Retour</button><h2>Fiche client</h2><input id=cid type=hidden value="${c?.id||""}"><label>Nom</label><input id=cnm value="${c?.name||""}"><label>Téléphone</label><input id=cp value="${c?.phone||""}"><label>Adresse</label><textarea id=ca>${c?.address||""}</textarea><label>Type</label><select id=cty><option>CESU</option><option>Location saisonnière</option><option>Particulier</option></select><label>Tarif</label><input id=cr type=number value="${c?.rate||db.settings.hourRate}"><button class=big onclick=saveClient()>💾 Enregistrer</button>`);if(c?.type)$("#cty").value=c.type}
function saveClient(){let id=$("#cid").value,o={id:id||uid(),name:$("#cnm").value,phone:$("#cp").value,address:$("#ca").value,type:$("#cty").value,rate:+$("#cr").value||db.settings.hourRate,notes:""};if(!o.name)return alert("Nom manquant");db.clients=id?db.clients.map(c=>c.id===id?{...c,...o}:c):[...db.clients,o];save();go("clients")}
function editInter(id){let x=id?db.interventions.find(i=>i.id===id):null,opts=clients().map(c=>`<option ${x?.client===c.name?"selected":""}>${c.name}</option>`).join("");layout(`<button onclick="go('interventions')">← Retour</button><h2>Saisie manuelle</h2><input id=eid type=hidden value="${x?.id||""}"><label>Client</label><select id=ec onchange=emach()>${opts}</select><label>Qui ?</label><select id=ew><option value=deux>À deux</option><option value=stephanie>Stéphanie</option><option value=jennyfer>Jennyfer</option></select><label>Type</label><input id=et value="${x?.type||"Ménage"}"><div id=emb class="card notice"><label>Machines Flo & Max</label><input id=em type=number value="${x?.machines||0}"></div><label>Date</label><input id=ed type=date value="${x?.date||today()}"><label>Arrivée</label><input id=es type=time value="${x?ft(new Date(x.start)):""}"><label>Départ</label><input id=ee type=time value="${x?ft(new Date(x.end)):""}"><label>Notes</label><textarea id=en>${x?.note||""}</textarea><button class="big blue" onclick=saveInter()>💾 Enregistrer</button>`);if(x)$("#ew").value=x.worker;emach()}
function emach(){if($("#emb"))$("#emb").style.display=$("#ec").value==="Floriane & Max"?"block":"none"}function saveInter(){let id=$("#eid").value,d=$("#ed").value,s=$("#es").value,e=$("#ee").value;if(!d||!s||!e)return alert("Date ou heures manquantes.");let st=new Date(`${d}T${s}:00`).toISOString(),en=new Date(`${d}T${e}:00`).toISOString(),cl=$("#ec").value,o={id:id||uid(),client:cl,worker:$("#ew").value,type:$("#et").value,machines:cl==="Floriane & Max"?(+$("#em").value||0):0,note:$("#en").value,start:st,end:en,date:d,duration:dur(st,en)};db.interventions=id?db.interventions.map(x=>x.id===id?o:x):[...db.interventions,o];save();go("interventions")}
function interventions(){let it=month().sort((a,b)=>new Date(b.start)-new Date(a.start));layout(`<button onclick="go('home')">← Retour</button><h2>Modifier heures</h2><button class=big onclick=editInter()>➕ Saisie manuelle</button>${it.map(x=>`<div class=item><div class=row><b>${x.client}</b><span class=pill>${fmin(x.duration)}</span></div><p>${fd(x.date)} • ${ft(new Date(x.start))} → ${ft(new Date(x.end))}<br>${worker(x.worker)}</p><div class=grid><button onclick="editInter('${x.id}')">✏️ Modifier</button><button class=stop onclick="delInter('${x.id}')">🗑️ Supprimer</button></div></div>`).join("")||"<div class=card>Aucune intervention.</div>"}`)}
function delInter(id){if(confirm("Supprimer ?")){db.interventions=db.interventions.filter(x=>x.id!==id);save();interventions()}}
function flomax(){let it=month().filter(x=>x.client==="Floriane & Max"),m=machines(it);layout(`<button onclick="go('home')">← Retour</button><h2>Floriane & Max</h2><div class=card><p>Machines : <b>${m}</b> = <b>${euros(m*db.settings.machinePrice)}</b></p></div><button class=big onclick=editInter()>➕ Ajouter</button>`)}
function planning(){let pl=db.planning.filter(p=>p.date?.startsWith(db.month)).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));layout(`<button onclick="go('home')">← Retour</button><h2>Planning</h2><button class=big onclick="go('google')">📅 Google Agenda / Importer</button>${pl.map(p=>`<div class=item><b>${p.client}</b><p>${fd(p.date)} ${p.time}<br>${p.type}</p><button class=big onclick="startFromPlan('${p.id}')">▶️ Démarrer le chrono</button></div>`).join("")||"<div class=card>Aucun planning. Va dans Google puis Importer mois.</div>"}`)}
function startFromPlan(id){let p=db.planning.find(x=>x.id===id);if(!p)return;let c=clients().find(x=>p.client?.toLowerCase().includes(x.name.toLowerCase()))?.name||p.client;db.current={client:c,worker:"deux",type:p.type||"Ménage",machines:c==="Floriane & Max"?0:0,note:"Depuis planning Google",start:new Date().toISOString(),planId:id};save();go("chrono")}
function google(){layout(`<button onclick="go('home')">← Retour</button><h2>Google Agenda</h2><div class=card><p>Compte : <b>${db.google.email}</b></p><p>État : <b>${db.google.accessToken&&Date.now()<db.google.expiresAt?"connecté":"non connecté"}</b></p></div><div class=card><label>Client ID Google</label><textarea id=g>${db.google.clientId||""}</textarea><button class=big onclick="db.google.clientId=$('#g').value.trim();save();alert('Client ID enregistré')">💾 Enregistrer</button></div><div class=grid><button onclick=connectGoogle()>🔐 Se connecter</button><button onclick=loadGoogleEvents()>⬇️ Importer mois</button><button onclick="window.open('https://calendar.google.com/calendar/u/0/r','_blank')">📅 Ouvrir</button></div>`)}
function connectGoogle(){if(!db.google.clientId)return alert("Colle le Client ID."); if(!window.google?.accounts?.oauth2)return alert("Attends 5 secondes."); tokenClient=google.accounts.oauth2.initTokenClient({client_id:db.google.clientId,scope:"https://www.googleapis.com/auth/calendar.events https://www.googleapis.com/auth/calendar.readonly",callback:r=>{if(r.error)return alert(r.error);db.google.accessToken=r.access_token;db.google.expiresAt=Date.now()+((r.expires_in||3600)-60)*1000;save();alert("Google connecté");go("google")}});tokenClient.requestAccessToken({prompt:"consent"})}
async function gfetch(url){return fetch(url,{headers:{Authorization:"Bearer "+db.google.accessToken}})}async function loadGoogleEvents(){try{let st=new Date(db.month+"-01T00:00:00"),en=new Date(st);en.setMonth(en.getMonth()+1);let r=await gfetch(`https://www.googleapis.com/calendar/v3/calendars/primary/events?timeMin=${encodeURIComponent(st.toISOString())}&timeMax=${encodeURIComponent(en.toISOString())}&singleEvents=true&orderBy=startTime&maxResults=80`);let data=await r.json(),c=0;(data.items||[]).forEach(ev=>{let dt=ev.start?.dateTime||ev.start?.date;if(!dt)return;if(!db.planning.find(p=>p.googleId===ev.id)){let summary=ev.summary||"RDV";db.planning.push({id:uid(),googleId:ev.id,date:dt.slice(0,10),time:ev.start?.dateTime?dt.slice(11,16):"09:00",client:guess(summary),type:summary});c++}});save();alert(c+" événement(s) importé(s)") ;go("planning")}catch(e){alert("Erreur import")}}
function guess(s){let f=db.clients.find(c=>s.toLowerCase().includes(c.name.toLowerCase().split(" ")[0]));return f?f.name:s}
function settings(){layout(`<button onclick="go('home')">← Retour</button><h2>Réglages</h2><div class="card ok"><p>Version V10 Finale.</p></div><div class=grid><button onclick="go('allRecap')">📋 Récap tous</button><button onclick="go('reports')">🔁 Reports</button><button onclick="go('closure')">🔒 Clôture</button><button onclick=exportData()>💾 Sauvegarde</button></div><div class=card><label>Mois affiché</label><input type=month value="${db.month}" onchange="db.month=this.value;save();go('home')"><label>Tarif horaire</label><input type=number value="${db.settings.hourRate}" onchange="db.settings.hourRate=+this.value;save()"><label>Prix machine Flo & Max</label><input type=number step=.01 value="${db.settings.machinePrice}" onchange="db.settings.machinePrice=+this.value;save()"></div><div class=card><button class=big onclick=exportData()>💾 Télécharger sauvegarde</button><label>Restaurer</label><input type=file onchange=importData(event)></div>`)}
function exportData(){let blob=new Blob([JSON.stringify(db,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="sauvegarde_steph_jenny_v10_finale.json";a.click()}
function importData(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{db=merge(def(),JSON.parse(r.result));save();go("home");alert("Sauvegarde restaurée")}catch(e){alert("Fichier invalide")}};r.readAsText(f)}
render();if("serviceWorker" in navigator){navigator.serviceWorker.register("sw.js").catch(()=>{})}
