
const STORE_KEY="sj_v8_finale_data";
const OLD_KEYS=["sj_v7_definitive_data","sj_v6_ultimate_data","sj_v5_pro_data","steph_jenny_v2_data"];
const GOOGLE_CALENDAR_URL="https://calendar.google.com/calendar/u/0/r";
const MAPS_URL=a=>"https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(a||"");
const DEFAULT_CLIENTS=["Nadège","Camille & Benoît","Thierry","Serge","Hélène","Juliette","Céline","Cabinet d'infirmières","Dorothée & Laurent","Élodie","Maryse","Véronique","Jean-Christophe","Nicole","Aymeric","Daniel","Jean-Claude","Richard","Kath","Floriane & Max"];
const uid=()=>crypto?.randomUUID?crypto.randomUUID():"id"+Date.now()+Math.random();
const defaultDB=()=>({version:"v8-finale",month:new Date().toISOString().slice(0,7),current:null,settings:{hourRate:16,machinePrice:2.5,company:"Steph & Jenny Gestion",googleCalendar:GOOGLE_CALENDAR_URL,googleEmail:"steph.jenny.menagecesu@gmail.com"},clients:DEFAULT_CLIENTS.map((name,i)=>({id:uid(),ref:(["Richard","Kath","Floriane & Max"].includes(name)?"G":"C")+String(i+1).padStart(3,"0"),name,phone:"",email:"",address:"",type:["Richard","Kath","Floriane & Max"].includes(name)?"Location saisonnière":"CESU",rate:16,archived:false,notes:""})),interventions:[],planning:[],closures:{},tasks:[],expenses:[]});
function merge(a,b){for(const k in b){a[k]=typeof b[k]==="object"&&!Array.isArray(b[k])&&b[k]!==null?merge(a[k]||{},b[k]):b[k]}return a}
function load(){try{let x=JSON.parse(localStorage.getItem(STORE_KEY));if(x)return merge(defaultDB(),x);for(const k of OLD_KEYS){let o=localStorage.getItem(k);if(o){x=merge(defaultDB(),JSON.parse(o));x.version="v8-finale";localStorage.setItem(STORE_KEY,JSON.stringify(x));return x}}return defaultDB()}catch(e){return defaultDB()}}
let db=load(), screen="home", lastScreen="home";
function save(){localStorage.setItem(STORE_KEY,JSON.stringify(db))}
const $=q=>document.querySelector(q), $$=q=>[...document.querySelectorAll(q)];
const pad=n=>String(n).padStart(2,"0"), today=()=>new Date().toISOString().slice(0,10);
const fmtDate=s=>s?new Date(s+"T00:00:00").toLocaleDateString("fr-FR"):"";
const longDate=s=>s?new Date(s+"T00:00:00").toLocaleDateString("fr-FR",{weekday:"long",day:"numeric",month:"long",year:"numeric"}):"";
const fmtTime=d=>`${pad(d.getHours())}:${pad(d.getMinutes())}`, euros=n=>Number(n||0).toFixed(2).replace(".",",")+" €";
const duration=(a,b)=>{const ms=new Date(b)-new Date(a);return ms>0?Math.max(1,Math.ceil(ms/60000)):0}, fmtDur=m=>`${m<0?"-":""}${Math.floor(Math.abs(m)/60)}h${pad(Math.abs(m)%60)}`;
const monthItems=(list=db.interventions)=>list.filter(x=>x.date?.startsWith(db.month));
const ckey=(client,month,who)=>`${client}|${month}|${who}`;
function prevMonth(m){let[y,mo]=m.split("-").map(Number);mo--;if(mo===0){mo=12;y--}return y+"-"+String(mo).padStart(2,"0")}
function carryIn(client,month,who){return db.closures?.[ckey(client,prevMonth(month),who)]?.carryOut||0}
function declaredHours(min){let sign=min<0?-1:1,abs=Math.abs(min),h=Math.floor(abs/60),r=abs%60;return sign*(r>=31?h+1:h)}
function calcReport(client,month,who,raw){let cin=carryIn(client,month,who),adjusted=raw+cin,declared=declaredHours(adjusted),carryOut=adjusted-declared*60;return{carryIn:cin,adjusted,declared,carryOut}}
function fmtReport(m){return m===0?"0 min":(m>0?"+":"")+m+" min"}function reportLabel(m){return m<0?`${fmtReport(m)} à déduire`:m>0?`${fmtReport(m)} à ajouter`:"0 min"}
function activeClients(){return db.clients.filter(c=>!c.archived)}function client(name){return db.clients.find(c=>c.name===name)||{name,rate:db.settings.hourRate,type:""}}
function personMinutes(items,who){return items.filter(x=>x.worker==="deux"||x.worker===who).reduce((a,x)=>a+(+x.duration||0),0)}
function machineCount(items){return items.filter(x=>x.client==="Floriane & Max").reduce((a,x)=>a+(+x.machines||0),0)}
function income(items){return items.reduce((a,x)=>a+(x.duration/60)*(client(x.client).rate||db.settings.hourRate),0)+machineCount(items)*db.settings.machinePrice}
function go(s){lastScreen=screen;screen=s;render()}function nav(){return `<div class="nav"><button class="${screen==='home'?'active':''}" onclick="go('home')">🏠<br>Accueil</button><button onclick="newIntervention()">➕<br>Ajouter</button><button class="${screen==='planning'?'active':''}" onclick="go('planning')">📅<br>Plan.</button><button class="${screen==='clients'?'active':''}" onclick="go('clients')">👥<br>Clients</button><button class="${screen==='settings'?'active':''}" onclick="go('settings')">⚙️<br>Réglages</button></div>`}
function layout(content){document.getElementById("app").innerHTML=`<main class="app">${content}${nav()}</main>`}
function render(){({home,clients,planning,summary,payroll,settings,reports,interventions,seasonal,tasks,stats,expenses,docs,help,google}[screen]||home)()}
function home(){const items=monthItems(),todayPlan=db.planning.filter(p=>p.date===today()).sort((a,b)=>a.time.localeCompare(b.time));const weekStart=new Date();weekStart.setDate(weekStart.getDate()-weekStart.getDay()+1);const ws=weekStart.toISOString().slice(0,10);const week=items.filter(x=>x.date>=ws),machines=machineCount(items);layout(`<div class="hero"><div class="muted">🌿 Bonjour Stéphanie</div><div class="logo">Steph & Jenny</div><div class="sub">GESTION V8</div><p>${longDate(today())}</p><p class="small">Version finale</p></div>${db.current?`<div class="card notice"><p>Intervention en cours</p><h2>${db.current.client}</h2><p>Commencée à ${fmtTime(new Date(db.current.start))}</p><button class="big stop" onclick="stopWork()">⏹ Terminer</button></div>`:`<button class="big" onclick="newIntervention()">▶ Commencer une intervention</button>`}<div class="grid"><button onclick="go('clients')">👥 Clients</button><button onclick="go('summary')">📄 Récapitulatif</button><button onclick="go('payroll')">💶 Fiche paie</button><button onclick="go('interventions')">✏️ Modifier heures</button><button onclick="go('seasonal')">🏡 Flo & Max</button><button onclick="go('google')">📅 Google Agenda</button><button onclick="go('tasks')">✅ Tâches</button><button onclick="go('stats')">📊 Stats</button></div><div class="card"><h3>Planning du jour</h3>${todayPlan.length?todayPlan.map(p=>`<p><b>${p.time}</b> • ${p.client}<br><span class="small">${p.type} • ${p.worker==="deux"?"À deux":p.worker==="stephanie"?"Stéphanie":"Jennifer"}</span></p>`).join(""):"<p class='small'>Aucune intervention prévue aujourd’hui.</p>"}</div><div class="card"><p>Ce mois-ci</p><div class="grid3"><div class="stat"><strong>${fmtDur(items.reduce((a,x)=>a+x.duration,0))}</strong><span>heures</span></div><div class="stat"><strong>${machines}</strong><span>machines Flo & Max</span></div><div class="stat"><strong>${euros(income(items))}</strong><span>estimé</span></div></div></div><div class="card"><p>Cette semaine</p><div class="grid3"><div class="stat"><strong>${fmtDur(week.reduce((a,x)=>a+x.duration,0))}</strong><span>heures</span></div><div class="stat"><strong>${week.length}</strong><span>interv.</span></div><div class="stat"><strong>${euros(income(week))}</strong><span>estimé</span></div></div></div>`)}

/* Google Agenda: liens + ajout événement + import CSV simple */
function google(){layout(`<button onclick="go('home')">← Retour</button><h2>Google Agenda</h2><div class="card ok"><p>Compte prévu : <b>${db.settings.googleEmail}</b></p><p class="small">Cette version ouvre Google Agenda et peut préparer un événement à ajouter. La synchronisation automatique complète Google demande une autorisation Google avancée ; on garde ici la méthode stable et simple.</p></div><div class="grid"><button class="big" onclick="window.open(db.settings.googleCalendar||'${GOOGLE_CALENDAR_URL}','_blank')">📅 Ouvrir Google Agenda</button><button onclick="planForm()">➕ Ajouter au planning</button></div><div class="card"><h3>Créer un événement Google depuis le planning</h3><p class="small">Ajoute d’abord le rendez-vous dans Planning, puis clique sur “Google”.</p>${db.planning.slice().sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).slice(0,10).map(p=>`<div class="item"><b>${p.client}</b><p>${fmtDate(p.date)} à ${p.time}</p><button onclick="openGoogleEvent('${p.id}')">📅 Google</button></div>`).join("")||"<p>Aucun planning.</p>"}</div><div class="card notice"><h3>Importer depuis un CSV</h3><p class="small">Format : date,heure,client,type. Exemple : 2026-07-03,09:00,Nadège,Ménage</p><input type="file" accept=".csv,text/csv" onchange="importPlanningCSV(event)"></div>`)}
function googleDate(date,time){return date.replaceAll("-","")+"T"+time.replace(":","")+"00"}
function openGoogleEvent(id){const p=db.planning.find(x=>x.id===id);if(!p)return;const c=client(p.client), start=googleDate(p.date,p.time), end=googleDate(p.date,addMinutes(p.time,120));const url="https://calendar.google.com/calendar/render?action=TEMPLATE&text="+encodeURIComponent(p.type+" - "+p.client)+"&dates="+start+"/"+end+"&details="+encodeURIComponent("Créé depuis Steph & Jenny Gestion V8")+"&location="+encodeURIComponent(c.address||"");window.open(url,"_blank")}
function addMinutes(time,min){let [h,m]=time.split(":").map(Number),d=new Date();d.setHours(h,m+min,0,0);return pad(d.getHours())+":"+pad(d.getMinutes())}
function importPlanningCSV(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{const lines=r.result.split(/\r?\n/).filter(Boolean);let count=0;for(const line of lines){const [date,time,client,type]=line.split(",").map(x=>(x||"").trim());if(/^\d{4}-\d{2}-\d{2}$/.test(date)&&time&&client){db.planning.push({id:uid(),date,time,client,type:type||"Ménage",worker:"deux"});count++}}save();alert(count+" rendez-vous importé(s).");go("planning")};r.readAsText(f)}

/* forms/interventions */
function newIntervention(editId=null){const x=editId?db.interventions.find(i=>i.id===editId):null,opts=activeClients().map(c=>`<option ${x?.client===c.name?"selected":""}>${c.name}</option>`).join("");layout(`<button onclick="go('home')">← Retour</button><h2>${x?"Modifier intervention":"Nouvelle intervention"}</h2><input id="editId" type="hidden" value="${x?.id||""}"><label>Client</label><select id="client" onchange="toggleMachines()">${opts}</select><label>Qui intervient ?</label><select id="worker"><option value="deux">À deux</option><option value="stephanie">Stéphanie seule</option><option value="jennifer">Jennifer seule</option></select><label>Type</label><select id="type"><option>Ménage</option><option>Location saisonnière</option><option>Machine</option><option>Repassage</option><option>Linge</option><option>État des lieux</option></select><div id="machineBox" class="card notice"><h3>Machines Floriane & Max</h3><p class="small">Facturées uniquement à Floriane & Max : ${euros(db.settings.machinePrice)} par machine.</p><label>Nombre de machines</label><input id="machines" type="number" value="${x?.machines||0}"></div><div class="card checks"><h3>Tâches rapides</h3>${["Aspirateur","Serpillière","Salle de bain","Cuisine","Draps","Serviettes","Torchons","Papier toilette","Éteindre machine","Désherbage"].map(t=>`<label><input type="checkbox" class="quickTask" value="${t}" ${x?.tasks?.includes(t)?"checked":""}> ${t}</label>`).join("")}</div><label>Note</label><textarea id="note">${x?.note||""}</textarea><div class="card"><label>Date</label><input id="date" type="date" value="${x?.date||today()}"><label>Arrivée</label><input id="start" type="time" value="${x?fmtTime(new Date(x.start)):""}"><label>Départ</label><input id="end" type="time" value="${x?fmtTime(new Date(x.end)):""}"><button class="big blue" onclick="saveManual()">💾 Enregistrer</button></div>${!x?`<button class="big" onclick="startWork()">▶ Démarrer maintenant</button>`:`<button class="stop" style="width:100%;margin-top:10px" onclick="deleteIntervention('${x.id}')">🗑️ Supprimer</button>`}`);if(x){$("#worker").value=x.worker;$("#type").value=x.type||"Ménage"}toggleMachines()}
function selectedTasks(){return $$(".quickTask:checked").map(x=>x.value)}function toggleMachines(){const isFlo=$("#client")?.value==="Floriane & Max";if($("#machineBox"))$("#machineBox").style.display=isFlo?"block":"none"}
function startWork(){db.current={client:$("#client").value,worker:$("#worker").value,type:$("#type").value,machines:$("#client").value==="Floriane & Max"?(+$("#machines").value||0):0,note:$("#note").value,tasks:selectedTasks(),start:new Date().toISOString()};save();go('home')}
function stopWork(){const end=new Date().toISOString();db.interventions.push({...db.current,id:uid(),end,date:db.current.start.slice(0,10),duration:duration(db.current.start,end)});db.current=null;save();go('home')}
function saveManual(){const id=$("#editId").value,d=$("#date").value,s=$("#start").value,e=$("#end").value;if(!d||!s||!e)return alert("Il manque la date ou les heures.");const start=new Date(`${d}T${s}:00`).toISOString(),end=new Date(`${d}T${e}:00`).toISOString(),clientName=$("#client").value,obj={id:id||uid(),client:clientName,worker:$("#worker").value,type:$("#type").value,machines:clientName==="Floriane & Max"?(+$("#machines").value||0):0,note:$("#note").value,tasks:selectedTasks(),start,end,date:d,duration:duration(start,end)};db.interventions=id?db.interventions.map(x=>x.id===id?obj:x):[...db.interventions,obj];save();go('interventions')}
function interventions(){const items=monthItems().sort((a,b)=>new Date(b.start)-new Date(a.start));layout(`<button onclick="go('home')">← Retour</button><h2>Modifier interventions</h2>${items.map(x=>`<div class="item"><div class="row"><b>${x.client}</b><span class="pill">${fmtDur(x.duration)}</span></div><div>${fmtDate(x.date)} • ${fmtTime(new Date(x.start))} → ${fmtTime(new Date(x.end))}</div><p class="small">${x.type||""} ${x.client==="Floriane & Max"&&x.machines?`• ${x.machines} machine(s)`:''}</p>${x.tasks?.length?`<p class="xs">${x.tasks.join(" · ")}</p>`:""}<p>${x.note||""}</p><div class="grid"><button onclick="newIntervention('${x.id}')">✏️ Modifier</button><button class="stop" onclick="deleteIntervention('${x.id}')">🗑️ Supprimer</button></div></div>`).join("")||"<div class='card'>Aucune intervention.</div>"}`)}
function deleteIntervention(id){if(confirm("Supprimer cette intervention ?")){db.interventions=db.interventions.filter(x=>x.id!==id);save();interventions()}}

/* clients */
function clients(){layout(`<button onclick="go('home')">← Retour</button><h2>Clients</h2><input placeholder="Rechercher..." oninput="filterClients(this.value)"><button class="big" onclick="clientForm()">➕ Ajouter un client</button><div id="clientList">${clientListHTML(db.clients)}</div>`)}
function clientListHTML(list){return list.map(c=>`<div class="item"><div class="row"><b>${c.name}</b><span class="pill">${c.archived?"Archivé":c.type}</span></div><p class="small">${c.ref} • ${c.phone||"Tél. non renseigné"}<br>${c.address||"Adresse non renseignée"}</p><div class="grid"><button onclick="clientForm('${c.id}')">✏️ Fiche</button><button onclick="summary('${c.name.replaceAll("'","\\'")}')">📄 Récap</button>${c.address?`<button onclick="window.open('${MAPS_URL(c.address)}','_blank')">🗺️ Maps</button>`:""}${c.phone?`<button onclick="location.href='tel:${c.phone}'">📞 Appel</button>`:""}</div></div>`).join("")}
function filterClients(q){q=q.toLowerCase();$("#clientList").innerHTML=clientListHTML(db.clients.filter(c=>(c.name+c.phone+c.address+c.type).toLowerCase().includes(q)))}
function clientForm(id=null){const c=id?db.clients.find(x=>x.id===id):{};layout(`<button onclick="go('clients')">← Retour</button><h2>Fiche client</h2><input id="cid" type="hidden" value="${c?.id||""}"><label>Référence</label><input id="ref" value="${c?.ref||""}"><label>Nom</label><input id="name" value="${c?.name||""}"><label>Téléphone</label><input id="phone" value="${c?.phone||""}"><label>Email</label><input id="email" value="${c?.email||""}"><label>Adresse</label><textarea id="address">${c?.address||""}</textarea><label>Type</label><select id="ctype"><option>CESU</option><option>Location saisonnière</option><option>Particulier</option></select><label>Tarif horaire</label><input id="rate" type="number" value="${c?.rate||db.settings.hourRate}"><label>Notes</label><textarea id="cnotes">${c?.notes||""}</textarea><button class="big" onclick="saveClient()">💾 Enregistrer</button>${c?.id?`<button class="stop" style="width:100%;margin-top:10px" onclick="archiveClient('${c.id}')">📦 Archiver</button>`:""}`);if(c?.type)$("#ctype").value=c.type}
function saveClient(){const id=$("#cid").value,obj={id:id||uid(),ref:$("#ref").value,name:$("#name").value,phone:$("#phone").value,email:$("#email").value,address:$("#address").value,type:$("#ctype").value,rate:+$("#rate").value||db.settings.hourRate,notes:$("#cnotes").value,archived:false};if(!obj.name)return alert("Nom manquant");db.clients=id?db.clients.map(c=>c.id===id?{...c,...obj}:c):[...db.clients,obj];save();go('clients')}
function archiveClient(id){const c=db.clients.find(c=>c.id===id);if(c&&confirm("Archiver ce client ?")){c.archived=true;save();go('clients')}}

/* recap/payroll */
function summary(name=null){const clientName=name||activeClients()[0]?.name,c=client(clientName),items=monthItems().filter(x=>x.client===clientName),steph=personMinutes(items,"stephanie"),jen=personMinutes(items,"jennifer"),cs=calcReport(clientName,db.month,"stephanie",steph),cj=calcReport(clientName,db.month,"jennifer",jen),machines=clientName==="Floriane & Max"?machineCount(items):0;layout(`<button onclick="go('home')">← Retour</button><h2>Récapitulatif</h2><select onchange="summary(this.value)">${db.clients.map(c=>`<option ${c.name===clientName?"selected":""}>${c.name}</option>`).join("")}</select><div class="card"><h2>${clientName}</h2><p class="small">${c.ref||""} • ${c.phone||""}<br>${c.address||""}</p><table><tr><th>Date</th><th>Arrivée</th><th>Départ</th><th>Durée</th></tr>${items.map(x=>`<tr><td>${fmtDate(x.date)}</td><td>${fmtTime(new Date(x.start))}</td><td>${fmtTime(new Date(x.end))}</td><td>${fmtDur(x.duration)}</td></tr>`).join("")}</table><h3>Reports</h3><p>Stéphanie : ${fmtDur(steph)} • précédent ${fmtReport(cs.carryIn)} • déclarer ${cs.declared}h • suivant ${reportLabel(cs.carryOut)}</p><p>Jennifer : ${fmtDur(jen)} • précédent ${fmtReport(cj.carryIn)} • déclarer ${cj.declared}h • suivant ${reportLabel(cj.carryOut)}</p>${machines?`<p><b>Machines Floriane & Max :</b> ${machines} × ${euros(db.settings.machinePrice)} = ${euros(machines*db.settings.machinePrice)}</p>`:""}</div><button onclick="window.print()" style="width:100%">🖨️ PDF / Imprimer</button>`)}
function payroll(){const names=[...new Set(monthItems().map(x=>x.client))];let totalS=0,totalJ=0,totalSA=0,totalJA=0,totalMachines=0;const rows=names.map(n=>{const c=client(n),items=monthItems().filter(x=>x.client===n),s=personMinutes(items,"stephanie"),j=personMinutes(items,"jennifer"),cs=calcReport(n,db.month,"stephanie",s),cj=calcReport(n,db.month,"jennifer",j),rate=c.rate||db.settings.hourRate,m=n==="Floriane & Max"?machineCount(items):0;totalS+=cs.declared;totalJ+=cj.declared;totalSA+=cs.declared*rate;totalJA+=cj.declared*rate;totalMachines+=m;return`<tr><td>${n}</td><td>${cs.declared}h<br>${euros(cs.declared*rate)}</td><td>${cj.declared}h<br>${euros(cj.declared*rate)}</td><td>${m?euros(m*db.settings.machinePrice):"-"}</td></tr>`}).join("");layout(`<button onclick="go('home')">← Retour</button><h2>Fiche paie globale</h2><div class="card"><p>Stéphanie : <b>${totalS}h</b> soit <b>${euros(totalSA)}</b></p><p>Jennifer : <b>${totalJ}h</b> soit <b>${euros(totalJA)}</b></p><p>Machines Flo & Max : <b>${totalMachines}</b> soit <b>${euros(totalMachines*db.settings.machinePrice)}</b></p><p>Total : <b>${totalS+totalJ}h</b> soit <b>${euros(totalSA+totalJA+totalMachines*db.settings.machinePrice)}</b></p></div><div class="card"><table><tr><th>Client</th><th>Stéphanie</th><th>Jennifer</th><th>Machines</th></tr>${rows}</table></div><button onclick="window.print()" style="width:100%">🖨️ PDF / Imprimer</button>`)}
function reports(){const entries=Object.entries(db.closures||{});layout(`<button onclick="go('settings')">← Retour</button><h2>Reports</h2>${entries.length?entries.map(([k,r])=>`<div class="item"><b>${k}</b><p>Réel ${fmtDur(r.raw||0)} • déclaré ${r.declared}h • report ${fmtReport(r.carryOut||0)}</p></div>`).join(""):"<div class='card'>Aucun mois clôturé.</div>"}`)}
function closeMonth(){if(!confirm("Clôturer le mois affiché ?"))return;const names=[...new Set(monthItems().map(x=>x.client))];names.forEach(n=>{const items=monthItems().filter(x=>x.client===n),s=personMinutes(items,"stephanie"),j=personMinutes(items,"jennifer");db.closures[ckey(n,db.month,"stephanie")]={...calcReport(n,db.month,"stephanie",s),raw:s};db.closures[ckey(n,db.month,"jennifer")]={...calcReport(n,db.month,"jennifer",j),raw:j}});save();alert("Mois clôturé. Les reports passeront au mois suivant.")}

/* planning/modules */
function planning(){const items=db.planning.filter(p=>p.date?.startsWith(db.month)).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));layout(`<button onclick="go('home')">← Retour</button><h2>Planning</h2><button class="big" onclick="planForm()">➕ Ajouter au planning</button><button class="outline" style="width:100%;margin-top:10px" onclick="go('google')">📅 Google Agenda</button>${items.map(p=>`<div class="item"><div class="row"><b>${p.client}</b><span class="pill">${p.time}</span></div><div>${fmtDate(p.date)} • ${p.type} • ${p.worker}</div><div class="grid"><button onclick="planForm('${p.id}')">✏️ Modifier</button><button onclick="openGoogleEvent('${p.id}')">📅 Google</button><button class="stop" onclick="deletePlan('${p.id}')">🗑️ Supprimer</button></div></div>`).join("")||"<div class='card'>Aucune intervention prévue.</div>"}`)}
function planForm(id=null){const p=id?db.planning.find(x=>x.id===id):{};layout(`<button onclick="go('planning')">← Retour</button><h2>Intervention prévue</h2><input id="pid" type="hidden" value="${p?.id||""}"><label>Client</label><select id="pclient">${activeClients().map(c=>`<option ${p?.client===c.name?"selected":""}>${c.name}</option>`)}</select><label>Date</label><input id="pdate" type="date" value="${p?.date||today()}"><label>Heure</label><input id="ptime" type="time" value="${p?.time||"09:00"}"><label>Type</label><select id="ptype"><option>Ménage</option><option>Location saisonnière</option><option>Machine</option><option>Repassage</option></select><label>Qui</label><select id="pworker"><option value="deux">À deux</option><option value="stephanie">Stéphanie</option><option value="jennifer">Jennifer</option></select><button class="big" onclick="savePlan()">💾 Enregistrer</button>`);if(p?.type)$("#ptype").value=p.type;if(p?.worker)$("#pworker").value=p.worker}
function savePlan(){const id=$("#pid").value,obj={id:id||uid(),client:$("#pclient").value,date:$("#pdate").value,time:$("#ptime").value,type:$("#ptype").value,worker:$("#pworker").value};db.planning=id?db.planning.map(p=>p.id===id?obj:p):[...db.planning,obj];save();go('planning')}function deletePlan(id){db.planning=db.planning.filter(p=>p.id!==id);save();go('planning')}
function seasonal(){const items=monthItems().filter(x=>x.client==="Floriane & Max"),machines=machineCount(items);layout(`<button onclick="go('home')">← Retour</button><h2>Floriane & Max</h2><div class="card notice"><h3>Machines</h3><p>Uniquement ici : <b>${euros(db.settings.machinePrice)}</b> par machine</p><p>Total mois : <b>${machines}</b> machine(s) = <b>${euros(machines*db.settings.machinePrice)}</b></p></div><button class="big" onclick="newIntervention()">➕ Ajouter une intervention / machine</button>${items.map(x=>`<div class="item"><b>${fmtDate(x.date)}</b><p>${fmtDur(x.duration)} ${x.machines?`• ${x.machines} machine(s)`:''}</p>${x.tasks?.length?`<p class="xs">${x.tasks.join(" · ")}</p>`:""}<p class="small">${x.note||""}</p></div>`).join("")||"<div class='card'>Aucune intervention ce mois-ci.</div>"}`)}
function tasks(){const done=db.tasks.filter(t=>t.done).length,total=db.tasks.length,p=total?Math.round(done/total*100):0;layout(`<button onclick="go('home')">← Retour</button><h2>Liste de tâches</h2><div class="card"><div class="progress"><span style="width:${p}%"></span></div><p>${done}/${total} terminé</p><label>Nouvelle tâche</label><input id="taskText" placeholder="Ex : penser aux rouleaux papier toilette"><button class="big" onclick="addTask()">Ajouter</button></div>${db.tasks.map(t=>`<div class="item row"><span>${t.done?"✅":"⬜"} ${t.text}</span><div><button onclick="toggleTask('${t.id}')">✓</button><button class="stop" onclick="deleteTask('${t.id}')">×</button></div></div>`).join("")||"<div class='card'>Aucune tâche.</div>"}`)}
function addTask(){if(!$("#taskText").value)return;db.tasks.push({id:uid(),text:$("#taskText").value,done:false});save();tasks()}function toggleTask(id){let t=db.tasks.find(t=>t.id===id);if(t)t.done=!t.done;save();tasks()}function deleteTask(id){db.tasks=db.tasks.filter(t=>t.id!==id);save();tasks()}
function stats(){const items=monthItems(),by={};items.forEach(x=>by[x.client]=(by[x.client]||0)+x.duration);const max=Math.max(1,...Object.values(by));layout(`<button onclick="go('home')">← Retour</button><h2>Statistiques</h2><div class="card"><p>Interventions : <b>${items.length}</b></p><p>Heures : <b>${fmtDur(items.reduce((a,x)=>a+x.duration,0))}</b></p><p>Machines Flo & Max : <b>${machineCount(items)}</b></p><p>CA estimé : <b>${euros(income(items))}</b></p></div>${Object.entries(by).sort((a,b)=>b[1]-a[1]).map(([n,m])=>`<div class="item"><div class="row"><b>${n}</b><span>${fmtDur(m)}</span></div><div class="progress"><span style="width:${Math.round(m/max*100)}%"></span></div></div>`).join("")||"<div class='card'>Pas encore de statistiques.</div>"}`)}
function expenses(){layout(`<button onclick="go('settings')">← Retour</button><h2>Dépenses</h2><div class="card"><label>Date</label><input id="edate" type="date" value="${today()}"><label>Libellé</label><input id="elabel"><label>Montant</label><input id="eamount" type="number" step="0.01"><button class="big" onclick="addExpense()">Ajouter</button></div>${db.expenses.filter(e=>e.date.startsWith(db.month)).map(e=>`<div class="item row"><span>${fmtDate(e.date)} • ${e.label}</span><b>${euros(e.amount)}</b></div>`).join("")||"<div class='card'>Aucune dépense ce mois.</div>"}`)}
function addExpense(){db.expenses.push({id:uid(),date:$("#edate").value,label:$("#elabel").value,amount:+$("#eamount").value||0});save();expenses()}
function docs(){layout(`<button onclick="go('home')">← Retour</button><h2>Documents</h2><div class="grid"><button onclick="go('summary')">📄 Récap client</button><button onclick="go('payroll')">💶 Fiche paie</button><button onclick="go('reports')">🔁 Reports</button><button onclick="exportData()">💾 Sauvegarde</button></div>`)}
function settings(){layout(`<button onclick="go('home')">← Retour</button><h2>Réglages</h2><div class="card ok"><h3>Version V8 finale</h3><p class="small">Tu peux commencer à rentrer tes clients et heures. Pas de devis, pas de facture, pas de rappel automatique.</p></div><div class="grid"><button onclick="go('docs')">📄 Documents</button><button onclick="go('expenses')">🧾 Dépenses</button><button onclick="go('reports')">🔁 Reports</button><button onclick="go('help')">❓ Aide</button></div><div class="card"><label>Mois affiché</label><input type="month" value="${db.month}" onchange="db.month=this.value;save();go('home')"><label>Tarif horaire par défaut</label><input type="number" value="${db.settings.hourRate}" onchange="db.settings.hourRate=+this.value;save()"><label>Prix machine Floriane & Max</label><input type="number" step="0.01" value="${db.settings.machinePrice}" onchange="db.settings.machinePrice=+this.value;save()"><label>Email Google Agenda</label><input value="${db.settings.googleEmail||''}" onchange="db.settings.googleEmail=this.value;save()"><label>Lien Google Agenda</label><input value="${db.settings.googleCalendar||GOOGLE_CALENDAR_URL}" onchange="db.settings.googleCalendar=this.value;save()"></div><div class="card"><button class="big" onclick="exportData()">💾 Télécharger la sauvegarde</button><label>Restaurer une sauvegarde</label><input type="file" onchange="importData(event)"></div><div class="card notice"><button class="big" onclick="closeMonth()">🔒 Clôturer le mois</button></div>`)}
function help(){layout(`<button onclick="go('settings')">← Retour</button><h2>Aide rapide</h2><div class="card"><h3>Pour commencer</h3><p>1. Va dans Clients pour compléter les fiches.<br>2. Va dans Planning ou Google Agenda pour préparer les rendez-vous.<br>3. Pour les heures : bouton Ajouter ou Commencer une intervention.<br>4. Les machines sont facturées seulement si le client est Floriane & Max.</p></div><div class="card notice"><h3>Sauvegarde</h3><p>Pense à télécharger une sauvegarde régulièrement dans Réglages.</p></div>`)}
function exportData(){const blob=new Blob([JSON.stringify(db,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="sauvegarde_steph_jenny_v8.json";a.click()}
function importData(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{db=merge(defaultDB(),JSON.parse(r.result));save();go('home');alert("Sauvegarde restaurée.")}catch(e){alert("Fichier invalide")}};r.readAsText(f)}
render();if("serviceWorker" in navigator){navigator.serviceWorker.register("sw.js").catch(()=>{})}
