
const STORE_KEY="sj_v9_google_data";
const OLD_KEYS=["sj_v8_finale_data","sj_v7_definitive_data","sj_v6_ultimate_data","sj_v5_pro_data"];
const DEFAULT_CLIENTS=["Nadège","Camille & Benoît","Thierry","Serge","Hélène","Juliette","Céline","Cabinet d'infirmières","Dorothée & Laurent","Élodie","Maryse","Véronique","Jean-Christophe","Nicole","Aymeric","Daniel","Jean-Claude","Richard","Kath","Floriane & Max"];
const GOOGLE_CALENDAR_URL="https://calendar.google.com/calendar/u/0/r";
const MAPS_URL=a=>"https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(a||"");
const uid=()=>crypto?.randomUUID?crypto.randomUUID():"id"+Date.now()+Math.random();
const defaultDB=()=>({version:"v9-google",month:new Date().toISOString().slice(0,7),current:null,google:{clientId:"",accessToken:"",expiresAt:0,email:"steph.jenny.menagecesu@gmail.com"},settings:{hourRate:16,machinePrice:2.5},clients:DEFAULT_CLIENTS.map((name,i)=>({id:uid(),ref:(["Richard","Kath","Floriane & Max"].includes(name)?"G":"C")+String(i+1).padStart(3,"0"),name,phone:"",email:"",address:"",type:["Richard","Kath","Floriane & Max"].includes(name)?"Location saisonnière":"CESU",rate:16,archived:false,notes:""})),interventions:[],planning:[],closures:{},tasks:[],expenses:[]});
function merge(a,b){for(const k in b){a[k]=typeof b[k]==="object"&&!Array.isArray(b[k])&&b[k]!==null?merge(a[k]||{},b[k]):b[k]}return a}
function load(){try{let x=JSON.parse(localStorage.getItem(STORE_KEY));if(x)return merge(defaultDB(),x);for(const k of OLD_KEYS){let o=localStorage.getItem(k);if(o){x=merge(defaultDB(),JSON.parse(o));x.version="v9-google";localStorage.setItem(STORE_KEY,JSON.stringify(x));return x}}return defaultDB()}catch(e){return defaultDB()}}
let db=load(), screen="home", tokenClient=null;function save(){localStorage.setItem(STORE_KEY,JSON.stringify(db))}
const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)],pad=n=>String(n).padStart(2,"0"),today=()=>new Date().toISOString().slice(0,10);
const fmtDate=s=>s?new Date(s+"T00:00:00").toLocaleDateString("fr-FR"):"", longDate=s=>s?new Date(s+"T00:00:00").toLocaleDateString("fr-FR",{weekday:"long",day:"numeric",month:"long",year:"numeric"}):"";
const fmtTime=d=>`${pad(d.getHours())}:${pad(d.getMinutes())}`, euros=n=>Number(n||0).toFixed(2).replace(".",",")+" €";
const duration=(a,b)=>Math.max(0,Math.ceil((new Date(b)-new Date(a))/60000)), fmtDur=m=>`${Math.floor(Math.abs(m)/60)}h${pad(Math.abs(m)%60)}`;
const monthItems=(list=db.interventions)=>list.filter(x=>x.date?.startsWith(db.month));
function client(name){return db.clients.find(c=>c.name===name)||{name,rate:db.settings.hourRate,type:""}} function activeClients(){return db.clients.filter(c=>!c.archived)}
function personMinutes(items,who){return items.filter(x=>x.worker==="deux"||x.worker===who).reduce((a,x)=>a+(+x.duration||0),0)}
function machineCount(items){return items.filter(x=>x.client==="Floriane & Max").reduce((a,x)=>a+(+x.machines||0),0)}
function income(items){return items.reduce((a,x)=>a+(x.duration/60)*(client(x.client).rate||db.settings.hourRate),0)+machineCount(items)*db.settings.machinePrice}
function declaredHours(min){let h=Math.floor(Math.abs(min)/60),r=Math.abs(min)%60,sg=min<0?-1:1;return sg*(r>=31?h+1:h)}
function go(s){screen=s;render()}function nav(){return `<div class="nav"><button onclick="go('home')">🏠<br>Accueil</button><button onclick="newIntervention()">➕<br>Ajouter</button><button onclick="go('planning')">📅<br>Plan.</button><button onclick="go('clients')">👥<br>Clients</button><button onclick="go('settings')">⚙️<br>Réglages</button></div>`}
function layout(c){document.getElementById("app").innerHTML=`<main class="app">${c}${nav()}</main>`}function render(){({home,clients,planning,google,summary,payroll,settings,interventions,seasonal,tasks,stats,docs}[screen]||home)()}
function home(){const items=monthItems(),todayPlan=db.planning.filter(p=>p.date===today()).sort((a,b)=>a.time.localeCompare(b.time));layout(`<div class="hero"><div class="small">🌿 Bonjour Stéphanie</div><div class="logo">Steph & Jenny</div><div class="sub">GESTION V9</div><p>${longDate(today())}</p><p class="small">Google Agenda inclus</p></div>${db.current?`<div class="card notice"><h2>${db.current.client}</h2><p>Commencée à ${fmtTime(new Date(db.current.start))}</p><button class="big stop" onclick="stopWork()">⏹ Terminer</button></div>`:`<button class="big" onclick="newIntervention()">▶ Commencer une intervention</button>`}<div class="grid"><button onclick="go('clients')">👥 Clients</button><button onclick="go('summary')">📄 Récap</button><button onclick="go('payroll')">💶 Paie</button><button onclick="go('interventions')">✏️ Heures</button><button onclick="go('seasonal')">🏡 Flo & Max</button><button onclick="go('google')">📅 Google</button><button onclick="go('tasks')">✅ Tâches</button><button onclick="go('stats')">📊 Stats</button></div><div class="card"><h3>Planning du jour</h3>${todayPlan.length?todayPlan.map(p=>`<p><b>${p.time}</b> • ${p.client}<br><span class="small">${p.type}</span></p>`).join(""):"<p class='small'>Aucune intervention prévue aujourd’hui.</p>"}</div><div class="card"><div class="grid3"><div class="stat"><strong>${fmtDur(items.reduce((a,x)=>a+x.duration,0))}</strong><span>heures</span></div><div class="stat"><strong>${machineCount(items)}</strong><span>machines</span></div><div class="stat"><strong>${euros(income(items))}</strong><span>estimé</span></div></div></div>`)}

/* Google */
function google(){const connected=db.google.accessToken&&Date.now()<db.google.expiresAt;layout(`<button onclick="go('home')">← Retour</button><h2>Google Agenda</h2><div class="card ${connected?'ok':'notice'}"><p>Compte : <b>${db.google.email}</b></p><p>État : <b>${connected?'connecté':'non connecté'}</b></p></div><div class="card"><label>Client ID Google</label><textarea id="gclient" placeholder="Colle l’ID client OAuth qui finit par .apps.googleusercontent.com">${db.google.clientId||""}</textarea><button class="big" onclick="saveGoogleId()">💾 Enregistrer</button><p class="small">Ne colle jamais le secret client.</p></div><div class="grid"><button onclick="connectGoogle()">🔐 Se connecter</button><button onclick="loadGoogleEvents()">⬇️ Importer mois</button><button onclick="window.open('${GOOGLE_CALENDAR_URL}','_blank')">📅 Ouvrir Agenda</button><button onclick="planForm()">➕ Planning</button></div><div class="card"><h3>Envoyer un RDV vers Google</h3>${db.planning.slice().sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).slice(0,20).map(p=>`<div class="item"><b>${p.client}</b><p>${fmtDate(p.date)} à ${p.time}</p><button onclick="createGoogleEvent('${p.id}')">📤 Envoyer</button></div>`).join("")||"<p>Aucun planning.</p>"}</div>`)}
function saveGoogleId(){db.google.clientId=$("#gclient").value.trim();save();alert("Client ID enregistré.");go("google")}
function connectGoogle(){if(!db.google.clientId)return alert("Colle d’abord le Client ID Google."); if(!window.google?.accounts?.oauth2)return alert("Google charge encore. Attends 5 secondes."); tokenClient=google.accounts.oauth2.initTokenClient({client_id:db.google.clientId,scope:"https://www.googleapis.com/auth/calendar.events https://www.googleapis.com/auth/calendar.readonly",callback:(resp)=>{if(resp.error){alert("Erreur Google : "+resp.error);return}db.google.accessToken=resp.access_token;db.google.expiresAt=Date.now()+((resp.expires_in||3600)-60)*1000;save();alert("Google Agenda connecté.");go("google")}});tokenClient.requestAccessToken({prompt:"consent"})}
async function googleFetch(url,opts={}){if(!db.google.accessToken||Date.now()>db.google.expiresAt){alert("Connecte-toi à Google Agenda.");go("google");throw new Error("No token")}return fetch(url,{...opts,headers:{...(opts.headers||{}),Authorization:"Bearer "+db.google.accessToken,"Content-Type":"application/json"}})}
function addMinutes(time,min){let[h,m]=time.split(":").map(Number),d=new Date();d.setHours(h,m+min,0,0);return pad(d.getHours())+":"+pad(d.getMinutes())}
async function createGoogleEvent(id){const p=db.planning.find(x=>x.id===id);if(!p)return;const c=client(p.client);try{const body={summary:`${p.type} - ${p.client}`,location:c.address||"",description:"Créé depuis Steph & Jenny Gestion V9",start:{dateTime:`${p.date}T${p.time}:00`,timeZone:"Europe/Paris"},end:{dateTime:`${p.date}T${addMinutes(p.time,120)}:00`,timeZone:"Europe/Paris"}};const r=await googleFetch("https://www.googleapis.com/calendar/v3/calendars/primary/events",{method:"POST",body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());alert("Ajouté dans Google Agenda.")}catch(e){alert("Erreur Google : "+e.message)}}
async function loadGoogleEvents(){try{let start=new Date(db.month+"-01T00:00:00"),end=new Date(start);end.setMonth(end.getMonth()+1);const url=`https://www.googleapis.com/calendar/v3/calendars/primary/events?timeMin=${encodeURIComponent(start.toISOString())}&timeMax=${encodeURIComponent(end.toISOString())}&singleEvents=true&orderBy=startTime&maxResults=80`;const r=await googleFetch(url);if(!r.ok)throw new Error(await r.text());const data=await r.json();let count=0;(data.items||[]).forEach(ev=>{const dt=ev.start?.dateTime||ev.start?.date;if(!dt)return;const date=dt.slice(0,10),time=ev.start?.dateTime?dt.slice(11,16):"09:00",summary=ev.summary||"Rendez-vous";if(!db.planning.find(p=>p.googleId===ev.id)){db.planning.push({id:uid(),googleId:ev.id,date,time,client:guessClient(summary),type:summary,worker:"deux"});count++}});save();alert(count+" événement(s) importé(s).");go("planning")}catch(e){alert("Erreur import : "+e.message)}}
function guessClient(s){let f=db.clients.find(c=>s.toLowerCase().includes(c.name.toLowerCase()));return f?f.name:s}

/* Interventions */
function newIntervention(editId=null){const x=editId?db.interventions.find(i=>i.id===editId):null,opts=activeClients().map(c=>`<option ${x?.client===c.name?"selected":""}>${c.name}</option>`).join("");layout(`<button onclick="go('home')">← Retour</button><h2>${x?"Modifier":"Nouvelle"} intervention</h2><input id="editId" type="hidden" value="${x?.id||""}"><label>Client</label><select id="client" onchange="toggleMachines()">${opts}</select><label>Qui ?</label><select id="worker"><option value="deux">À deux</option><option value="stephanie">Stéphanie</option><option value="jennifer">Jennifer</option></select><label>Type</label><select id="type"><option>Ménage</option><option>Location saisonnière</option><option>Machine</option><option>Repassage</option></select><div id="machineBox" class="card notice"><h3>Machines Floriane & Max</h3><label>Nombre</label><input id="machines" type="number" value="${x?.machines||0}"></div><label>Note</label><textarea id="note">${x?.note||""}</textarea><div class="card"><label>Date</label><input id="date" type="date" value="${x?.date||today()}"><label>Arrivée</label><input id="start" type="time" value="${x?fmtTime(new Date(x.start)):""}"><label>Départ</label><input id="end" type="time" value="${x?fmtTime(new Date(x.end)):""}"><button class="big blue" onclick="saveManual()">💾 Enregistrer</button></div>${!x?`<button class="big" onclick="startWork()">▶ Démarrer maintenant</button>`:`<button class="stop" onclick="deleteIntervention('${x.id}')">🗑️ Supprimer</button>`}`);if(x){$("#worker").value=x.worker;$("#type").value=x.type||"Ménage"}toggleMachines()}
function toggleMachines(){if($("#machineBox"))$("#machineBox").style.display=$("#client")?.value==="Floriane & Max"?"block":"none"}
function startWork(){db.current={client:$("#client").value,worker:$("#worker").value,type:$("#type").value,machines:$("#client").value==="Floriane & Max"?(+$("#machines").value||0):0,note:$("#note").value,start:new Date().toISOString()};save();go("home")}
function stopWork(){const end=new Date().toISOString();db.interventions.push({...db.current,id:uid(),end,date:db.current.start.slice(0,10),duration:duration(db.current.start,end)});db.current=null;save();go("home")}
function saveManual(){const id=$("#editId").value,d=$("#date").value,s=$("#start").value,e=$("#end").value;if(!d||!s||!e)return alert("Date ou heures manquantes.");const start=new Date(`${d}T${s}:00`).toISOString(),end=new Date(`${d}T${e}:00`).toISOString(),cl=$("#client").value,obj={id:id||uid(),client:cl,worker:$("#worker").value,type:$("#type").value,machines:cl==="Floriane & Max"?(+$("#machines").value||0):0,note:$("#note").value,start,end,date:d,duration:duration(start,end)};db.interventions=id?db.interventions.map(x=>x.id===id?obj:x):[...db.interventions,obj];save();go("interventions")}
function interventions(){const items=monthItems().sort((a,b)=>new Date(b.start)-new Date(a.start));layout(`<button onclick="go('home')">← Retour</button><h2>Modifier heures</h2>${items.map(x=>`<div class="item"><div class="row"><b>${x.client}</b><span class="pill">${fmtDur(x.duration)}</span></div><p>${fmtDate(x.date)} • ${fmtTime(new Date(x.start))} → ${fmtTime(new Date(x.end))}</p><p>${x.note||""}</p><div class="grid"><button onclick="newIntervention('${x.id}')">✏️ Modifier</button><button class="stop" onclick="deleteIntervention('${x.id}')">🗑️ Supprimer</button></div></div>`).join("")||"<div class='card'>Aucune intervention.</div>"}`)}
function deleteIntervention(id){if(confirm("Supprimer ?")){db.interventions=db.interventions.filter(x=>x.id!==id);save();interventions()}}

/* Clients etc */
function clients(){layout(`<button onclick="go('home')">← Retour</button><h2>Clients</h2><input placeholder="Rechercher..." oninput="filterClients(this.value)"><button class="big" onclick="clientForm()">➕ Ajouter</button><div id="clientList">${clientListHTML(db.clients)}</div>`)}
function clientListHTML(list){return list.map(c=>`<div class="item"><div class="row"><b>${c.name}</b><span class="pill">${c.type}</span></div><p class="small">${c.ref} • ${c.phone||"Tél. non renseigné"}<br>${c.address||"Adresse non renseignée"}</p><div class="grid"><button onclick="clientForm('${c.id}')">✏️ Fiche</button><button onclick="summary('${c.name.replaceAll("'","\\'")}')">📄 Récap</button>${c.address?`<button onclick="window.open('${MAPS_URL(c.address)}','_blank')">🗺️ Maps</button>`:""}${c.phone?`<button onclick="location.href='tel:${c.phone}'">📞 Appel</button>`:""}</div></div>`).join("")}
function filterClients(q){q=q.toLowerCase();$("#clientList").innerHTML=clientListHTML(db.clients.filter(c=>(c.name+c.phone+c.address+c.type).toLowerCase().includes(q)))}
function clientForm(id=null){const c=id?db.clients.find(x=>x.id===id):{};layout(`<button onclick="go('clients')">← Retour</button><h2>Fiche client</h2><input id="cid" type="hidden" value="${c?.id||""}"><label>Réf</label><input id="ref" value="${c?.ref||""}"><label>Nom</label><input id="name" value="${c?.name||""}"><label>Téléphone</label><input id="phone" value="${c?.phone||""}"><label>Email</label><input id="email" value="${c?.email||""}"><label>Adresse</label><textarea id="address">${c?.address||""}</textarea><label>Type</label><select id="ctype"><option>CESU</option><option>Location saisonnière</option><option>Particulier</option></select><label>Tarif</label><input id="rate" type="number" value="${c?.rate||db.settings.hourRate}"><label>Notes</label><textarea id="cnotes">${c?.notes||""}</textarea><button class="big" onclick="saveClient()">💾 Enregistrer</button>`);if(c?.type)$("#ctype").value=c.type}
function saveClient(){const id=$("#cid").value,obj={id:id||uid(),ref:$("#ref").value,name:$("#name").value,phone:$("#phone").value,email:$("#email").value,address:$("#address").value,type:$("#ctype").value,rate:+$("#rate").value||db.settings.hourRate,notes:$("#cnotes").value,archived:false};if(!obj.name)return alert("Nom manquant");db.clients=id?db.clients.map(c=>c.id===id?{...c,...obj}:c):[...db.clients,obj];save();go("clients")}
function summary(name=null){const clientName=name||activeClients()[0]?.name,items=monthItems().filter(x=>x.client===clientName),s=personMinutes(items,"stephanie"),j=personMinutes(items,"jennifer"),m=clientName==="Floriane & Max"?machineCount(items):0;layout(`<button onclick="go('home')">← Retour</button><h2>Récapitulatif</h2><select onchange="summary(this.value)">${db.clients.map(c=>`<option ${c.name===clientName?"selected":""}>${c.name}</option>`).join("")}</select><div class="card"><h2>${clientName}</h2><table><tr><th>Date</th><th>Arrivée</th><th>Départ</th><th>Durée</th></tr>${items.map(x=>`<tr><td>${fmtDate(x.date)}</td><td>${fmtTime(new Date(x.start))}</td><td>${fmtTime(new Date(x.end))}</td><td>${fmtDur(x.duration)}</td></tr>`).join("")}</table><p>Stéphanie : ${fmtDur(s)} • déclarer ${declaredHours(s)}h</p><p>Jennifer : ${fmtDur(j)} • déclarer ${declaredHours(j)}h</p>${m?`<p>Machines : ${m} × ${euros(db.settings.machinePrice)} = ${euros(m*db.settings.machinePrice)}</p>`:""}</div><button onclick="window.print()">🖨️ PDF</button>`)}
function payroll(){const names=[...new Set(monthItems().map(x=>x.client))];let total=0;const rows=names.map(n=>{const c=client(n),items=monthItems().filter(x=>x.client===n),mins=personMinutes(items,"stephanie")+personMinutes(items,"jennifer"),h=declaredHours(mins),m=n==="Floriane & Max"?machineCount(items):0,amount=h*(c.rate||db.settings.hourRate)+m*db.settings.machinePrice;total+=amount;return`<tr><td>${n}</td><td>${h}h</td><td>${m||"-"}</td><td>${euros(amount)}</td></tr>`}).join("");layout(`<button onclick="go('home')">← Retour</button><h2>Fiche paie globale</h2><div class="card"><table><tr><th>Client</th><th>Heures</th><th>Machines</th><th>Total</th></tr>${rows}</table><h3>Total : ${euros(total)}</h3></div><button onclick="window.print()">🖨️ PDF</button>`)}
function planning(){const items=db.planning.filter(p=>p.date?.startsWith(db.month)).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));layout(`<button onclick="go('home')">← Retour</button><h2>Planning</h2><button class="big" onclick="planForm()">➕ Ajouter</button><button onclick="go('google')">📅 Google Agenda</button>${items.map(p=>`<div class="item"><div class="row"><b>${p.client}</b><span>${p.time}</span></div><p>${fmtDate(p.date)} • ${p.type}</p><div class="grid"><button onclick="planForm('${p.id}')">✏️ Modifier</button><button onclick="createGoogleEvent('${p.id}')">📤 Google</button><button class="stop" onclick="deletePlan('${p.id}')">🗑️</button></div></div>`).join("")||"<div class='card'>Aucun planning.</div>"}`)}
function planForm(id=null){const p=id?db.planning.find(x=>x.id===id):{};layout(`<button onclick="go('planning')">← Retour</button><h2>Rendez-vous</h2><input id="pid" type="hidden" value="${p?.id||""}"><label>Client</label><select id="pclient">${activeClients().map(c=>`<option ${p?.client===c.name?"selected":""}>${c.name}</option>`)}</select><label>Date</label><input id="pdate" type="date" value="${p?.date||today()}"><label>Heure</label><input id="ptime" type="time" value="${p?.time||"09:00"}"><label>Type</label><input id="ptype" value="${p?.type||"Ménage"}"><button class="big" onclick="savePlan()">💾 Enregistrer</button>`)}
function savePlan(){const id=$("#pid").value,obj={id:id||uid(),client:$("#pclient").value,date:$("#pdate").value,time:$("#ptime").value,type:$("#ptype").value,worker:"deux"};db.planning=id?db.planning.map(p=>p.id===id?obj:p):[...db.planning,obj];save();go("planning")}function deletePlan(id){db.planning=db.planning.filter(p=>p.id!==id);save();planning()}
function seasonal(){const items=monthItems().filter(x=>x.client==="Floriane & Max"),m=machineCount(items);layout(`<button onclick="go('home')">← Retour</button><h2>Floriane & Max</h2><div class="card notice"><p>Machines : <b>${m}</b> = <b>${euros(m*db.settings.machinePrice)}</b></p></div><button class="big" onclick="newIntervention()">➕ Ajouter</button>${items.map(x=>`<div class="item"><b>${fmtDate(x.date)}</b><p>${fmtDur(x.duration)} ${x.machines?`• ${x.machines} machine(s)`:''}</p></div>`).join("")||"<div class='card'>Aucune intervention.</div>"}`)}
function tasks(){layout(`<button onclick="go('home')">← Retour</button><h2>Tâches</h2><div class="card"><input id="taskText"><button onclick="addTask()">Ajouter</button></div>${db.tasks.map(t=>`<div class="item row"><span>${t.done?"✅":"⬜"} ${t.text}</span><button onclick="toggleTask('${t.id}')">✓</button></div>`).join("")||"<div class='card'>Aucune tâche.</div>"}`)}
function addTask(){if(!$("#taskText").value)return;db.tasks.push({id:uid(),text:$("#taskText").value,done:false});save();tasks()}function toggleTask(id){let t=db.tasks.find(t=>t.id===id);if(t)t.done=!t.done;save();tasks()}
function stats(){const items=monthItems();layout(`<button onclick="go('home')">← Retour</button><h2>Stats</h2><div class="card"><p>Interventions : <b>${items.length}</b></p><p>Heures : <b>${fmtDur(items.reduce((a,x)=>a+x.duration,0))}</b></p><p>Machines Flo & Max : <b>${machineCount(items)}</b></p><p>CA estimé : <b>${euros(income(items))}</b></p></div>`)}
function docs(){layout(`<button onclick="go('home')">← Retour</button><h2>Documents</h2><div class="grid"><button onclick="go('summary')">Récap</button><button onclick="go('payroll')">Paie</button><button onclick="exportData()">Sauvegarde</button></div>`)}
function settings(){layout(`<button onclick="go('home')">← Retour</button><h2>Réglages</h2><div class="card ok"><p>Version V9 Google. Ne colle jamais le secret client.</p></div><div class="grid"><button onclick="go('docs')">📄 Documents</button><button onclick="go('google')">📅 Google</button></div><div class="card"><label>Mois</label><input type="month" value="${db.month}" onchange="db.month=this.value;save();go('home')"><label>Tarif horaire</label><input type="number" value="${db.settings.hourRate}" onchange="db.settings.hourRate=+this.value;save()"><label>Prix machine Flo & Max</label><input type="number" step="0.01" value="${db.settings.machinePrice}" onchange="db.settings.machinePrice=+this.value;save()"></div><div class="card"><button class="big" onclick="exportData()">💾 Sauvegarde</button><label>Restaurer</label><input type="file" onchange="importData(event)"></div>`)}
function exportData(){const blob=new Blob([JSON.stringify(db,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="sauvegarde_steph_jenny_v9.json";a.click()}
function importData(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{db=merge(defaultDB(),JSON.parse(r.result));save();go("home");alert("Sauvegarde restaurée.")}catch(e){alert("Fichier invalide")}};r.readAsText(f)}
render();if("serviceWorker" in navigator){navigator.serviceWorker.register("sw.js").catch(()=>{})}
